import {createConstants} from '../utils/reduxHelper';

export default {
  // 登陆
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // 注册
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  // 注册发送验证码
  SEND_CODE_SUCCESS: 'SEND_CODE_SUCCESS',


  // 媒体列表
  MEDIA_LIST_FETCH_REQUEST: 'MEDIA_LIST_FETCH_REQUEST',
  MEDIA_LIST_FETCH_SUCCESS: 'MEDIA_LIST_FETCH_SUCCESS',
  MEDIA_LIST_FETCH_FAILURE: 'MEDIA_LIST_FETCH_FAILURE',

  // 媒体表单获取
  MEDIA_FORM_FETCH_REQUEST: 'MEDIA_FORM_FETCH_REQUEST',
  MEDIA_FORM_FETCH_SUCCESS: 'MEDIA_FORM_FETCH_REQUEST',
  MEDIA_FORM_FETCH_FAILURE: 'MEDIA_FORM_FETCH_REQUEST',

  // 媒体表单提交
  MEDIA_FORM_SUBMIT_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  MEDIA_FORM_SUBMIT_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  MEDIA_FORM_SUBMIT_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',


  MEDIA_FORM_SUBMIT: 'MEDIA_FORM_SUBMIT',

  // 广告位列表
  AD_LIST_FETCH_REQUEST: 'AD_LIST_FETCH_REQUEST',
  AD_LIST_FETCH_SUCCESS: 'AD_LIST_FETCH_SUCCESS',
  AD_LIST_FETCH_FAILURE: 'AD_LIST_FETCH_FAILURE',

  // 广告位表单获取
  AD_FORM_FETCH_REQUEST: 'AD_FORM_FETCH_REQUEST',
  AD_FORM_FETCH_SUCCESS: 'AD_FORM_FETCH_REQUEST',
  AD_FORM_FETCH_FAILURE: 'AD_FORM_FETCH_REQUEST',

  // 媒体表单提交
  AD_FORM_SUBMIT_REQUEST: 'AD_FORM_SUBMIT_REQUEST',
  AD_FORM_SUBMIT_SUCCESS: 'AD_FORM_SUBMIT_REQUEST',
  AD_FORM_SUBMIT_FAILURE: 'AD_FORM_SUBMIT_REQUEST',

  // 媒体表单更新
  AD_FORM_UPDATE_REQUEST: 'AD_FORM_UPDATE_REQUEST',
  AD_FORM_UPDATE_SUCCESS: 'AD_FORM_UPDATE_REQUEST',
  AD_FORM_UPDATE_FAILURE: 'AD_FORM_UPDATE_REQUEST',


  // 屏蔽策略
  SHIELD_LIST_FETCH: 'SHIELD_LIST_FETCH',

  // 屏蔽策略提交
  SHIELD_FORM_FETCH_REQUEST: 'SHIELD_FORM_FETCH_REQUEST',
  SHIELD_FORM_FETCH_SUCCESS: 'SHIELD_FORM_FETCH_SUCCESS',
  SHIELD_FORM_FETCH_FAILURE: 'SHIELD_FORM_FETCH_FAILURE',

  // 屏蔽策略更新
  SHIELD_FORM_UPDATE_REQUEST: 'SHIELD_FORM_UPDATE_REQUEST',
  SHIELD_FORM_UPDATE_SUCCESS: 'SHIELD_FORM_UPDATE_SUCCESS',
  SHIELD_FORM_UPDATE_FAILURE: 'SHIELD_FORM_UPDATE_FAILURE',

  SHIELD_FORM_SUBMIT: 'SHIELD_FORM_SUBMIT',

  SHIELD_FORM_SET: 'SHIELD_FORM_SET',


  INDUSTRY_LIST_FETCH_SUCCESS: 'INDUSTRY_LIST_FETCH_SUCCESS',

  // 用户
  USER_INFO_FETCH: 'USER_INFO_FETCH',

}
