import {createConstants} from '../utils/reduxHelper';

export default {
  // 登陆
  LOGIN_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  LOGIN_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  LOGIN_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  // 注册
  REGISTER_REQUEST: 'REGISTER_REQUEST',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  // 注册发送验证码
  SEND_CODE_SUCCESS: 'SEND_CODE_SUCCESS',


  // 媒体表单
  MEDIA_FORM_SUBMIT_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  MEDIA_FORM_SUBMIT_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  MEDIA_FORM_SUBMIT_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  MEDIA_LIST_FETCH: 'MEDIA_LIST_FETCH',
  MEDIA_FORM_SUBMIT: 'MEDIA_FORM_SUBMIT',

  // 广告位
  AD_LIST_FETCH: 'AD_LIST_FETCH',
  AD_FORM_SUBMIT: 'AD_FORM_SUBMIT',

  // 屏蔽策略
  SHIELD_LIST_FETCH: 'SHIELD_LIST_FETCH',
  SHIELD_FORM_SUBMIT: 'SHIELD_FORM_SUBMIT',

  // 用户
  USER_INFO_FETCH: 'USER_INFO_FETCH',

}
