import {createConstants} from '../utils/reduxHelper';

export default {
  CALCULATE_FUEL_SAVINGS: 'MEDIA_FORM_SUBMIT_REQUEST',
  SAVE_FUEL_SAVINGS: 'MEDIA_FORM_SUBMIT_REQUEST',

  // 登陆
  LOGIN_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  LOGIN_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  LOGIN_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  // 媒体表单
  MEDIA_FORM_SUBMIT_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  MEDIA_FORM_SUBMIT_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  MEDIA_FORM_SUBMIT_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  MEDIA_LIST_FETCH: 'MEDIA_LIST_FETCH',
  // demo
  USER_FETCH_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  USER_FETCH_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  USER_FETCH_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  PROGRESSBAR_START: 'MEDIA_FORM_SUBMIT_REQUEST',
  PROGRESSBAR_STOP: 'MEDIA_FORM_SUBMIT_REQUEST',
  PROGRESSBAR_SET_VALUE: 'MEDIA_FORM_SUBMIT_REQUEST',

  SIGN_IN_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  SIGN_IN_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  SIGN_IN_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  SIGN_UP_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  SIGN_UP_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  SIGN_UP_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  SIGN_OUT_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  SIGN_OUT_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  SIGN_OUT_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  NOTIFICATIONS_CREATE: 'MEDIA_FORM_SUBMIT_REQUEST',
  NOTIFICATIONS_CREATE_WITH_ID: 'MEDIA_FORM_SUBMIT_REQUEST',
  NOTIFICATIONS_REMOVE: 'MEDIA_FORM_SUBMIT_REQUEST',

  MODAL_SHOW: 'MEDIA_FORM_SUBMIT_REQUEST',
  MODAL_HIDE: 'MEDIA_FORM_SUBMIT_REQUEST',

  SEARCH_REQUEST: 'MEDIA_FORM_SUBMIT_REQUEST',
  SEARCH_SUCCESS: 'MEDIA_FORM_SUBMIT_REQUEST',
  SEARCH_FAILURE: 'MEDIA_FORM_SUBMIT_REQUEST',

  SEARCH_RESET: 'MEDIA_FORM_SUBMIT_REQUEST',

  SCROLL_BOTTOM: 'SCROLL_BOTTOM'
}
